name: Udagram Microservices Project

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  first_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Reverse Proxy Image to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -t henokhm/reverseproxy:v11 ./udagram-reverseproxy
        docker push henokhm/reverseproxy:v11


  second_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Backend User Service Image to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -t henokhm/udagram-api-user:v11 ./udagram-api-user
        docker push henokhm/udagram-api-user:v11


  third_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Backend Feed Service Image to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -t henokhm/udagram-api-feed:v11 ./udagram-api-feed
        docker push henokhm/udagram-api-feed:v11


  forth_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Frontend Image to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -t henokhm/udagram-frontend:v11 ./udagram-frontend
        docker push henokhm/udagram-frontend:v11
